version: "3.7"
services:
  backend:
    build: ./backend
    ports:
      - 80:80
    env_file:
      - ./env/mongo.env
  redis:
    image: redis
  celery-worker:
    build: ./services
    command: celery -A tasks worker -l info
    depends_on:
      - redis
    env_file:
      - ./env/mongo.env
  celery-beat:
    build: ./services
    command: celery -A tasks beat -l info
    depends_on:
      - redis
    env_file:
      - ./env/mongo.env
