version: "3.7"
services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - 5000:5000
  #   env_file:
  #     - ./env/mongo.env
  redis:
    image: redis
  celery-worker:
    build: ./services
    command: celery -A tasks worker -l info
    depends_on:
      - redis
    env_file:
      - ./env/mongo.env
    # volumes:
    #   - ./services:/code
  celery-beat:
    build: ./services
    command: celery -A tasks beat -l info
    depends_on:
      - redis
    env_file:
      - ./env/mongo.env
    # volumes:
    #   - ./services:/code
